server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # SPA: cualquier ruta que no sea un archivo real, cae a index.html
    # (necesario para que funcione react-router-dom al refrescar/entrar directo a una URL)
    location / {
        try_files $uri /index.html;
    }
}
